"""
Packet Service for VAYA Authorize (Module D).
Handles Phase C (Document Assembly) and Phase D (Dispatcher/Cleanup).
"""

import os
import json
import zipfile
import shutil
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Tuple
from pathlib import Path

# Using lxml for XML validation as requested
try:
    from lxml import etree
except ImportError:
    etree = None

class PacketService:
    """
    The Architect & Dispatcher.
    Handles document assembly, validation, and packet packaging.
    """
    
    def __init__(self, storage_dir: str = "G:\\VAYA\\backend\\temp_storage"):
        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        self.expiry_map = {} # In-memory mock for "Tagging" in this demo version

    def generate_declaration_of_honour(self, data: Dict[str, Any]) -> str:
        """
        Step 1: Template Filling.
        Generates a styled HTML Declaration of Honour.
        (Using HTML as a robust, dependency-free alternative to PDF for this environment).
        """
        filename = f"Declaration_of_Honour_{data.get('application_id')}.html"
        filepath = self.storage_dir / filename
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: 'Times New Roman', serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 20px; }}
                h1 {{ text-align: center; text-transform: uppercase; font-size: 18pt; margin-bottom: 40px; }}
                .meta {{ margin-bottom: 30px; }}
                .section {{ margin-bottom: 20px; }}
                .signature {{ margin-top: 60px; border-top: 1px solid black; width: 300px; padding-top: 10px; }}
                .footer {{ margin-top: 50px; font-size: 10pt; text-align: center; color: #666; }}
            </style>
        </head>
        <body>
            <h1>Declaration of Honour on Exclusion Criteria</h1>
            
            <div class="meta">
                <strong>Entity Name:</strong> {data.get("entity_name")}<br>
                <strong>EORI Number:</strong> {data.get("eori_number")}<br>
                <strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d')}
            </div>
            
            <div class="section">
                The undersigned, representing the entity listed above, hereby certifies and declares on their honour that:
            </div>
            
            <div class="section">
                <ol>
                    <li>The entity has <strong>not</strong> been involved in any serious infringements of customs legislation or taxation rules in the last 5 years.</li>
                    <li>The entity has no record of serious criminal offenses relating to its economic activity.</li>
                    <li>The entity is not subject to insolvency, winding-up, or bankruptcy proceedings.</li>
                    <li>All applicable customs duties, taxes, and import charges have been paid in full.</li>
                </ol>
            </div>
            
            <div class="section">
                <strong>Financial Health Status:</strong> {data.get("solvency_status")}
            </div>
            
            <div class="signature">
                Signature of Authorized Representative
            </div>
            
            <div class="footer">
                Generated by VAYA Authorize Module - EU CBAM Compliance
            </div>
        </body>
        </html>
        """
        
        with open(filepath, "w") as f:
            f.write(html_content)
            
        return str(filepath)

    def generate_amm_xml(self, data: Dict[str, Any]) -> Tuple[str, bytes]:
        """
        Step 2b: XML Generation.
        Generates validates XML content for the EU AMM system.
        Returns (filepath, xml_bytes).
        """
        import xml.etree.ElementTree as ET
        
        root = ET.Element("AuthorizationApplication", xmlns="http://eu.amm.customs/v1")
        
        # Header
        meta = ET.SubElement(root, "Metadata")
        ET.SubElement(meta, "GeneratedAt").text = datetime.now().isoformat()
        ET.SubElement(meta, "ApplicationID").text = data.get("application_id")
        
        # Entity Details
        entity = ET.SubElement(root, "Applicant")
        ET.SubElement(entity, "EORI").text = data.get("eori_number")
        ET.SubElement(entity, "Name").text = data.get("entity_name")
        ET.SubElement(entity, "MemberState").text = data.get("country_code", "EU")
        
        # Financials
        fin = ET.SubElement(root, "FinancialHealth")
        ET.SubElement(fin, "Status").text = data.get("solvency_status", "UNKNOWN")
        ET.SubElement(fin, "GuaranteeAmountEUR").text = str(data.get("guarantee_amount", 0.0))
        
        # Convert to string
        xml_str = ET.tostring(root, encoding='utf-8', method='xml')
        
        filename = f"Export_AMM_{data.get('application_id')}.xml"
        filepath = self.storage_dir / filename
        
        with open(filepath, "wb") as f:
            f.write(xml_str)
            
        return str(filepath), xml_str

    def validate_amm_xml(self, xml_content: bytes) -> Tuple[bool, Optional[str]]:
        """
        Step 3: XML Validation (lxml).
        Checks if the data matches the EU AMM schema.
        """
        if etree is None:
            return True, "Validation skipped: lxml not installed"
            
        # Helper to create a dummy schema for demonstration if file missing
        schema_path = Path("eu_amm_schema_v2026.xsd")
        if not schema_path.exists():
            # Create a dummy XSD for the sake of the code actually running in demo
            with open(schema_path, "w") as f:
                f.write("""
                <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
                  <xs:element name="AuthorizationApplication">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="EORI" type="xs:string"/>
                        <xs:element name="EntityName" type="xs:string"/>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:schema>
                """)
        
        try:
            schema_doc = etree.parse(str(schema_path))
            schema = etree.XMLSchema(schema_doc)
            
            parser = etree.XMLParser(schema=schema)
            etree.fromstring(xml_content, parser)
            return True, None
        except etree.XMLSyntaxError as e:
            return False, str(e)
        except Exception as e:
            return False, str(e)

    def assemble_packet(self, application_id: str, file_paths: List[str]) -> str:
        """
        Final Delivery: Storage.
        Zips the SOP, Financials, and Declaration into a single packet.
        """
        zip_filename = f"Authorization_Packet_{application_id}.zip"
        zip_path = self.storage_dir / zip_filename
        
        with zipfile.ZipFile(zip_path, 'w') as zf:
            for file_path in file_paths:
                if os.path.exists(file_path):
                    zf.write(file_path, arcname=os.path.basename(file_path))
                else:
                    print(f"Warning: File {file_path} not found during assembly.")
        
        # Phase C Step 2: Tag for Cleanup
        self._tag_for_cleanup(str(zip_path))
        
        return str(zip_path)

    def _tag_for_cleanup(self, file_path: str):
        """
        Step 2: The 'Flush Promise'.
        Tag raw images/files with expiry_timestamp = now() + 24hrs.
        """
        expiry = datetime.now() + timedelta(hours=24)
        self.expiry_map[file_path] = expiry
        # In production this would write object metadata to S3 or a DB table

    def cleanup_expired_data(self):
        """
        Cron Job simulation.
        Deletes all objects with expired tags.
        """
        now = datetime.now()
        expired_files = [f for f, exp in self.expiry_map.items() if exp < now]
        
        for f in expired_files:
            try:
                if os.path.exists(f):
                    os.remove(f)
                del self.expiry_map[f]
                print(f"Cleaned up expired file: {f}")
            except Exception as e:
                print(f"Error cleaning {f}: {e}")

